<a href="https://colab.research.google.com/github/BohdanShepel2005/Numerical-Methods-of-Programming/blob/main/%D0%9B%D0%91_%E2%84%964.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Задаємо матриці A і B
A = np.array([[2, 3, 1], [-1, 1, 0], [1, 2, -1]])
B = np.array([[1, 2, 1], [0, 1, 2], [3, 1, 1]])

# Знайти матрицю C = AB - BA
C = np.dot(A, B) - np.dot(B, A)

print("Матриця C = AB - BA:")
print(C)

# Задаємо матрицю A
A = np.array([[0, 2, 0], [3, 4, 5], [6, 7, 8]])

# Обчислюємо визначник матриці
det_A = np.linalg.det(A)

print("Визначник матриці A:")
print(det_A)

# Задаємо нову матрицю
A = np.array([[5, 8, -4], [6, 9, -5], [4, 7, -3]])

# Підносимо матрицю A до квадрату (степінь 2)
A_squared = np.linalg.matrix_power(A, 2)

print("Матриця A піднесена до степеня 2:")
print(A_squared)

# Знаходимо добуток матриць A і B
prod_AB = np.dot(A, B)

print("Добуток матриць A і B:")
print(prod_AB)

# Знаходимо обернену матрицю
A_inv = np.linalg.inv(A)

print("Обернена матриця:")
print(A_inv)

# Задаємо нову матрицю
A_new = np.array([[2, 3, 4, 1], [1, 2, 3, 4], [3, 4, 1, 2], [4, 1, 2, 3]])

# Обчислюємо визначник нової матриці
det_A_new = np.linalg.det(A_new)

print("Визначник нової матриці A_new:")
print(det_A_new)

# Визначаємо ранг матриці
rank_A = np.linalg.matrix_rank(A_new)

print("Ранг матриці:")
print(rank_A)

Матриця C = AB - BA:
[[ 4  1  9]
 [-2 -6  3]
 [-8 -9  2]]
Визначник матриці A:
12.0
Матриця A піднесена до степеня 2:
[[ 57  84 -48]
 [ 64  94 -54]
 [ 50  74 -42]]
Добуток матриць A і B:
[[-7 14 17]
 [-9 16 19]
 [-5 12 15]]
Обернена матриця:
[[-1.50119988e+15  7.50599938e+14  7.50599938e+14]
 [ 3.75299969e+14 -1.87649984e+14 -1.87649984e+14]
 [-1.12589991e+15  5.62949953e+14  5.62949953e+14]]
Визначник нової матриці A_new:
-160.00000000000009
Ранг матриці:
4


In [ ]:
import numpy as np

# Метод матриці
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))
    return solutions

# Метод Гауса
def gauss_method(a, b):
    n = len(b)
    x = np.zeros(n)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]
    if any(np.isnan(x)) or any(np.isinf(x)):
        return None
    else:
        return x

def main():
    # Приклад матриці A та вектора B для розв'язку системи рівнянь Ax = B
    A = np.array([[4, 1, 4], [1, 1, 2], [2, 1, 2]])
    B = np.array([-2, -1, 0])

    # Матричний метод
    X_matrix = matrix_method(A, B)
    print("Матричний метод:", X_matrix)

    # Метод Крамера
    X_cramer = cramer_method(A, B)
    print("Метод Крамера:", X_cramer)

    # Метод Гауса
    X_gauss = gauss_method(A, B)
    if X_gauss is not None:
        print("Метод Гауса:", X_gauss)
    else:
        print("Метод Гауса не має розв'язків")

if __name__ == "__main__":
    main()

Матричний метод: [ 1.  2. -2.]
Метод Крамера: [1.0, 2.0, -2.0]
Метод Гауса не має розв'язків


<ipython-input-9-54711af132be>:29: RuntimeWarning: divide by zero encountered in scalar divide
  x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]


In [ ]:
import numpy as np
import sympy as sp

# Метод матриці
def matrix_method(coefficients, constants):
    inverse_matrix = np.linalg.inv(coefficients)
    return np.dot(inverse_matrix, constants)

# Метод Крамера
def cramer_method(coefficients, constants):
    det_coefficients = np.linalg.det(coefficients)
    solutions = []
    for i in range(len(coefficients)):
        modified_coefficients = np.copy(coefficients)
        modified_coefficients[:, i] = constants
        solutions.append(round(np.linalg.det(modified_coefficients) / det_coefficients, 1))
    return solutions

# Метод Гауса
def gauss_method(a, b):
    n = len(b)
    x = np.zeros(n)
    for k in range(0, n-1):
        for i in range(k+1, n):
            if a[i, k] != 0.0:
                lam = a[i, k] / a[k, k]
                a[i, k+1:n] = a[i, k+1:n] - lam * a[k, k+1:n]
                b[i] = b[i] - lam * b[k]
    for k in range(n-1, -1, -1):
        x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]
    if any(np.isnan(x)) or any(np.isinf(x)):
        return None
    else:
        return x

# Символьне розв'язання системи рівнянь
def sympy_solve(coefficients, constants):
    n = len(constants)
    x = sp.symbols('x:'+str(n))
    eqs = [sp.Eq(sum(coefficients[i, j] * x[j] for j in range(n)), constants[i]) for i in range(n)]
    sol = sp.solve(eqs, x)
    return [sol[var] for var in x]

def main():
    # Приклад матриці A та вектора B для розв'язку системи рівнянь Ax = B
    A = np.array([[4, 1, 4], [1, 1, 2], [2, 1, 2]])
    B = np.array([-2, -1, 0])

    # Вивід системи рівнянь
    x1, x2, x3 = sp.symbols('x1 x2 x3')
    eq1 = sp.Eq(4*x1 + x2 + 4*x3, -2)
    eq2 = sp.Eq(x1 + x2 + 2*x3, -1)
    eq3 = sp.Eq(2*x1 + x2 + 2*x3, 0)
    system_eqs = [eq1, eq2, eq3]

    print("Система рівнянь:")
    for eq in system_eqs:
        print(eq)

    # Матричний метод
    X_matrix = matrix_method(A, B)
    print("Матричний метод:", X_matrix)

    # Метод Крамера
    X_cramer = cramer_method(A, B)
    print("Метод Крамера:", X_cramer)

    # Метод Гауса
    X_gauss = gauss_method(A, B)
    if X_gauss is not None:
        print("Метод Гауса:", X_gauss)
    else:
        print("Метод Гауса не має розв'язків")

    # Символьне розв'язання
    X_sympy = sympy_solve(A, B)
    print("Символьне розв'язання:", X_sympy)

if __name__ == "__main__":
    main()

Система рівнянь:
Eq(4*x1 + x2 + 4*x3, -2)
Eq(x1 + x2 + 2*x3, -1)
Eq(2*x1 + x2 + 2*x3, 0)
Матричний метод: [ 1.  2. -2.]
Метод Крамера: [1.0, 2.0, -2.0]
Метод Гауса не має розв'язків
Символьне розв'язання: [1/2, -2, -1/2]


<ipython-input-1-b4b4bb713ea8>:30: RuntimeWarning: divide by zero encountered in scalar divide
  x[k] = (b[k] - np.dot(a[k, k+1:n], x[k+1:n])) / a[k, k]


In [ ]:
import numpy as np

def main(N, M):
    # Генеруємо прямокутну матрицю з випадковими елементами
    matrix = np.random.rand(N, M)

    # Знаходимо середні значення для кожного рядка матриці
    row_means = np.mean(matrix, axis=1)

    # Знаходимо найнижче значення серед середніх значень рядків
    min_mean = np.min(row_means)

    return min_mean

# Задаємо розміри матриці
N = 5  # кількість рядків
M = 3  # кількість стовпців

# Викликаємо функцію та виводимо результат
result = main(N, M)
print("Найнижче значення серед середніх значень для кожного рядка матриці:", result)

Найнижче значення серед середніх значень для кожного рядка матриці: 0.18062294728741293
